// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlczO1njI2X-ypxwJVtXDXege3w4qeLYg',
    appId: '1:438938015013:web:7a8dc7c57eec89a1d436cc',
    messagingSenderId: '438938015013',
    projectId: 'chat-app-77ebf',
    authDomain: 'chat-app-77ebf.firebaseapp.com',
    storageBucket: 'chat-app-77ebf.appspot.com',
    measurementId: 'G-6T3SXVGEF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5T92VttMXjtvzaCR1U-GAs4v3H4w3mfo',
    appId: '1:438938015013:android:97bfced3cb05d0abd436cc',
    messagingSenderId: '438938015013',
    projectId: 'chat-app-77ebf',
    storageBucket: 'chat-app-77ebf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg8QeeRrKYMUBlO7O7h9aHBPKZxokzCTA',
    appId: '1:438938015013:ios:308ca736582690d3d436cc',
    messagingSenderId: '438938015013',
    projectId: 'chat-app-77ebf',
    storageBucket: 'chat-app-77ebf.appspot.com',
    iosBundleId: 'com.example.edulearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg8QeeRrKYMUBlO7O7h9aHBPKZxokzCTA',
    appId: '1:438938015013:ios:308ca736582690d3d436cc',
    messagingSenderId: '438938015013',
    projectId: 'chat-app-77ebf',
    storageBucket: 'chat-app-77ebf.appspot.com',
    iosBundleId: 'com.example.edulearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlczO1njI2X-ypxwJVtXDXege3w4qeLYg',
    appId: '1:438938015013:web:75568f8e7db62df5d436cc',
    messagingSenderId: '438938015013',
    projectId: 'chat-app-77ebf',
    authDomain: 'chat-app-77ebf.firebaseapp.com',
    storageBucket: 'chat-app-77ebf.appspot.com',
    measurementId: 'G-F8PKGTWL4R',
  );
}
